package com.qwe7002.telegram_sms.value;

import okhttp3.MediaType;

public class constValue {
    public static final MediaType JSON = MediaType.get("application/json; charset=utf-8");
    public static final String BROADCAST_STOP_SERVICE = "com.qwe7002.telegram_sms.stop_all";
    public static final String NOTIFICATION_CHANNEL_CHAT_COMMAND = "chat_command";
    public static final String NOTIFICATION_CHANNEL_BATTERY = "battery_monitor";
    public static final String NOTIFICATION_CHANNEL_RESEND = "message_resend";
    public static final String NOTIFICATION_CHANNEL_NOTIFICATION = "notification";
    public static final String NOTIFICATION_CHANNEL_CHAT_COMMAND_SYSTEM = "chat_command_system";
    public static final String NOTIFICATION_CHANNEL_CHAT_COMMAND_SYSTEM_ID = "1";
    public static final String NOTIFICATION_CHANNEL_CHAT_COMMAND_ID = "2";
    public static final String NOTIFICATION_CHANNEL_BATTERY_ID = "3";
    public static final String NOTIFICATION_CHANNEL_RESEND_ID = "4";
    public static final String NOTIFICATION_CHANNEL_NOTIFICATION_ID = "5";
    public static final String SYSTEM_CONFIG_TAG = "system_config";
    public static final String SYSTEM_NETCHECK_RESULT = "netcheck_result";
    public static final String SYSTEM_MESSAGE_ID = "message_id";
    public static final String SYSTEM_RESEND_QUEUE = "resend_queue";
    public static final String SYSTEM_USSD_QUEUE = "ussd_queue";
    public static final String SYSTEM_GET_SPAM_LIST = "spam_list";
    public static final String SYSTEM_NOTIFY_APPS_LIST = "notify_apps_list";
    public static final String SYSTEM_NOTIFY_APPS_TITLE_LIST = "notify_apps_title_list";
    public static final String SYSTEM_NOTIFY_APPS_CONTENT_LIST = "notify_apps_content_list";
    public static final String SYSTEM_NOTIFY_APPS_ICON_LIST = "notify_apps_icon_list";
    public static final String SYSTEM_NOTIFY_APPS_PACKAGE_LIST = "notify_apps_package_list";
    public static final String SYSTEM_NOTIFY_APPS_ENABLED_LIST = "notify_apps_enabled_list";
    public static final String SYSTEM_NOTIFY_APPS_CHAT_ID_LIST = "notify_apps_chat_id_list";
    public static final String SYSTEM_NOTIFY_APPS_CHAT_TOKEN_LIST = "notify_apps_chat_token_list";
    public static final String SYSTEM_NOTIFY_APPS_CHAT_THREAD_ID_LIST = "notify_apps_chat_thread_id_list";
    public static final String SYSTEM_NOTIFY_APPS_CHAT_DISABLE_NOTIFY_LIST = "notify_apps_chat_disable_notify_list";
    public static final String SYSTEM_NOTIFY_APPS_CHAT_DISABLE_WEB_PREVIEW_LIST = "notify_apps_chat_disable_web_preview_list";
    public static final String SYSTEM_NOTIFY_APPS_CHAT_MERGE_LIST = "notify_apps_chat_merge_list";
    public static final String SYSTEM_NOTIFY_APPS_CHAT_SPLIT_LIST = "notify_apps_chat_split_list";
    public static final String SYSTEM_NOTIFY_APPS_CHAT_SPLIT_LONG_MESSAGE_LIST = "notify_apps_chat_split_long_message_list";
    public static final String SYSTEM_NOTIFY_APPS_CHAT_SPLIT_LONG_MESSAGE_LIMIT_LIST = "notify_apps_chat_split_long_message_limit_list";
    public static final String SYSTEM_NOTIFY_APPS_CHAT_SPLIT_LONG_MESSAGE_LIMIT_DEFAULT = "4000";
    public static final String SYSTEM_NOTIFY_APPS_CHAT_SPLIT_LONG_MESSAGE_DEFAULT = "false";
    public static final String SYSTEM_NOTIFY_APPS_CHAT_MERGE_DEFAULT = "false";
    public static final String SYSTEM_NOTIFY_APPS_CHAT_SPLIT_DEFAULT = "false";
    public static final String SYSTEM_NOTIFY_APPS_CHAT_DISABLE_NOTIFY_DEFAULT = "false";
    public static final String SYSTEM_NOTIFY_APPS_CHAT_DISABLE_WEB_PREVIEW_DEFAULT = "false";
    public static final String SYSTEM_NOTIFY_APPS_CHAT_TOKEN_DEFAULT = "";
    public static final String SYSTEM_NOTIFY_APPS_CHAT_ID_DEFAULT = "";
    public static final String SYSTEM_NOTIFY_APPS_CHAT_THREAD_ID_DEFAULT = "";
    public static final String SYSTEM_NOTIFY_APPS_ENABLED_DEFAULT = "false";
    public static final String SYSTEM_NOTIFY_APPS_PACKAGE_DEFAULT = "";
    public static final String SYSTEM_NOTIFY_APPS_ICON_DEFAULT = "";
    public static final String SYSTEM_NOTIFY_APPS_CONTENT_DEFAULT = "";
    public static final String SYSTEM_NOTIFY_APPS_TITLE_DEFAULT = "";
    public static final String SYSTEM_NOTIFY_APPS_DEFAULT = "";
    public static final String SYSTEM_GET_SPAM_LIST_DEFAULT = "";
    public static final String SYSTEM_USSD_QUEUE_DEFAULT = "";
    public static final String SYSTEM_RESEND_QUEUE_DEFAULT = "";
    public static final String SYSTEM_MESSAGE_ID_DEFAULT = "";
    public static final String SYSTEM_NETCHECK_RESULT_DEFAULT = "";
    public static final String SYSTEM_CONFIG_TAG_DEFAULT = "";
    public static final String NOTIFICATION_CHANNEL_NOTIFICATION_ID_DEFAULT = "";
    public static final String NOTIFICATION_CHANNEL_RESEND_ID_DEFAULT = "";
    public static final String NOTIFICATION_CHANNEL_BATTERY_ID_DEFAULT = "";
    public static final String NOTIFICATION_CHANNEL_CHAT_COMMAND_ID_DEFAULT = "";
    public static final String NOTIFICATION_CHANNEL_CHAT_COMMAND_SYSTEM_ID_DEFAULT = "";
    public static final String NOTIFICATION_CHANNEL_NOTIFICATION_DEFAULT = "";
    public static final String NOTIFICATION_CHANNEL_RESEND_DEFAULT = "";
    public static final String NOTIFICATION_CHANNEL_BATTERY_DEFAULT = "";
    public static final String NOTIFICATION_CHANNEL_CHAT_COMMAND_DEFAULT = "";
    public static final String NOTIFICATION_CHANNEL_CHAT_COMMAND_SYSTEM_DEFAULT = "";
    public static final String BROADCAST_STOP_SERVICE_DEFAULT = "";
    public static final String JSON_DEFAULT = "";
}
